### ISSUE TITLE
[1.12.2] Help With Loot

### ISSUE THREAD

**Issue by GWSheridan** [Leviathan143/LootTweaker#36] opened 2018-01-03 21:40 UTC
Trying to add loot to a mob but i seem to have hit a snag. This what i have tried

import loottweaker.vanilla.loot.LootTables;
import loottweaker.vanilla.loot.LootTable;
import loottweaker.vanilla.loot.LootPool;
import loottweaker.vanilla.loot.Functions;

//add leather
val blazing_juggernautTable = LootTables.getTable("primitivemobs:entities/blazing_juggernaut");
val blazing_juggernautPool = blazing_juggernautTable.addPool("leather", 0, 1, 0, 0);
val leather = <minecraft:leather>;
blazing_juggernautPool.addItemEntry(leather, 1);

Then I tried this way

import loottweaker.vanilla.loot.LootTables;
import loottweaker.vanilla.loot.LootTable;
import loottweaker.vanilla.loot.LootPool;
import loottweaker.vanilla.loot.Functions;

//Value
val blazing_juggernautTable = LootTables.getTable("primitivemobs:entities/blazing_juggernaut");
blazing_juggernaut.addPool("loot", 3, 64, 0, 0);
val blazingloot = blazing_juggernaut.getPool("loot");
blazingloot.addItemEntry(minecraft:leather, 1);

LootTweaker:  1.12-0.0.6.5
CraftTweaker/Minetweaker:  1.12-4.0.12
Forge:  14.23.1.2583
Minecraft:  1.12.2

**Comment by Leviathan143** [comment] 2018-01-03 23:34
`minecraft:leather` should be `<minecraft:leather>`.

**Comment by GWSheridan** [comment] 2018-01-04 15:04
ye have it set out like that. Just dont know how to put it on github like you have just done

**Comment by Leviathan143** [comment] 2018-01-04 18:33
Oh right, < & > symbols are part of markdown syntax, so you you usually need to escape them. It's better to use a paste site like pastebin or hastebin. Don't screenshot text, then it can't be copy-pasted. Instead it has to be typed out manually, which is time consuming and annoying.

Now, what exactly doesn't work? You've just given me a script, and told me "i seem to have hit a snag", so I have no idea what your problem is.

**Comment by GWSheridan** [comment] 2018-01-04 19:25
Okay sorry for that
The problem in having is the to syntax i have tried will not add leather to a mob for a drop when killed. Either by player or normal death

This is the syntax I have used these 2 version of the syntax an still no drops from the mob
 
version 1 https://pastebin.com/5d1Rh9hy
version 2 https://pastebin.com/w4Zc7URf

The mob is from primitive mobs version 1.1.4b_beta

LootTweaker: 1.12-0.0.6.5
CraftTweaker/Minetweaker: 1.12-4.0.12
Forge: 14.23.1.2583
Minecraft: 1.12.2

**Comment by Leviathan143** [comment] 2018-01-04 23:20
Works fine for me. If it's not working for you, some other mod is interfering.

**Comment by GWSheridan** [comment] 2018-01-05 00:22
Ye im also have problems with recipe changes now

**Comment by Leviathan143** [comment] 2018-01-12 20:33
Right, since this is non-reproducable, if there are no further comments within the next 7 days I will be closing this.

**Closed** 2018-01-21 21:14 UTC
Labels: 1.12, can't reproduce
