### ISSUE TITLE
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by a-frenzy** [Leviathan143/LootTweaker#75] opened 2020-03-02 14:10 UTC
Crash on world load

https://gist.github.com/frenzye/13e025493e322e9a7b8afbf5f898494c

**Comment by Daomephsta** [comment] 2020-03-02 18:33
Duplicate of #70. Check for an existing issue before creating a new one. 
Also follow the template when creating a new issue,  I ask for particular information for a reason.

**Closed as completed by Daomephsta** 2020-03-02 18:33 UTC
Labels: bug, duplicate
