### ISSUE TITLE
Hang at world load

### ISSUE THREAD

**Issue by ThisisCanada98** [Leviathan143/LootTweaker#17] opened 2017-05-04 00:48 UTC
After installing LootTweaker to my custom pack non of my worlds will load up. Even if I use scripts that work, such as from Foolcraft. Since it doesn't result in a crash I will upload the lasted Forge log

[latest.log.txt](https://github.com/Leviathan143/LootTweaker/files/975018/latest.log.txt)

**Comment by Leviathan143** [comment] 2017-05-04 04:58
Please supply the script used to create the posted report.

**Comment by Leviathan143** [comment] 2017-05-04 05:20
Also, could you please try [this](https://drive.google.com/open?id=0B_IqTUgN98IXU0JKWVNYR2pKWkk) jar to see if it fixes the issue? It has a fix for an issue I noticed while investigating this. I think the issue fixed might be related to this issue.

**Comment by ThisisCanada98** [comment] 2017-05-04 20:53
Alright tried the new jar and seem to get the same crash. I will upload
 the scripts, which ive taken from Foolcraft and modified for my own pack. 

[scripts.zip](https://github.com/Leviathan143/LootTweaker/files/977536/scripts.zip)

**Comment by Leviathan143** [comment] 2017-05-07 02:45
If you could narrow this issue down to a particular script, I would greatly appreciate it.

**Comment by Leviathan143** [comment] 2017-05-14 01:30
@ThisisCanada98 Please try 0.0.6.2 to see if it fixes this issue.

**Comment by Leviathan143** [comment] 2017-05-16 03:47
@ThisisCanada98 As I am unable to reproduce this bug, if you do not reply within 7 days to tell me whether 0.0.6.2 fixes this issue, I will assume that it is fixed (as I have recieved no other reports of this issue) and close the issue.

**Comment by Leviathan143** [comment] 2017-05-31 05:34
Closing

**Closed by Leviathan143** 2017-05-31 05:34 UTC
Labels: 1.10.2, can't reproduce
