### ISSUE TITLE
Crash with loottweaker and lootbags on 1.12.2

### ISSUE THREAD

**Issue by Saereth** [Leviathan143/LootTweaker#64] opened 2019-12-11 10:33 UTC
**Describe the bug**
Whenever I load up loottweaker and lootbags I get a crash, disabling either mod resolves this issue. 

**To Reproduce**
Add loottweaker and lootbags to my 1.12 instance and attempt to launch, get a crash error with this error: https://gist.github.com/Saereth/ca12058657a9b8379f91d25d7cc39470

**Expected behavior**
Hopefully not crash

**Logs & scripts**
This happens with no loot scripts enabled.

**Version Info (Exact versions only):**
LootTweaker: 	LootTweaker-0.1.3+MC1.12.2
CraftTweaker/Minetweaker: CraftTweaker2-1.12-4.1.20
Forge: 14.23.5.2847
Minecraft: 1.12.2
LootBags: LootBags-1.12.2-2.5.8.5

**Additional context**
Also posted on lootbag's github here: https://github.com/Malorolam/LootBags/issues/203

**Comment by Daomephsta** [comment] 2019-12-11 20:20
> This happens with no loot scripts enabled.

There are definitely scripts enabled, the method that's causing the crash is never called in LootTweaker itself.

The issue itself has the same root cause as #62. It's already fixed in dev, I'm just waiting on people to test a test JAR before I release. I've had too many major issues reported right after release lately.
The crash is caused by faulty error handling, so it won't happen if there aren't any errors to report. You've got an entry name wrong in whatever script is still enabled.

**Closed as completed by Daomephsta** 2019-12-11 20:20 UTC
Labels: bug

**Comment by Saereth** [comment] 2019-12-11 22:38
just FYI, I'm using the jar you posted there and it did resolve the crash, even when I re-enabled all my loot scripts. I'll continue using and see if I run into any other issues to help test. Any other features you want me to test on this experimental jar? Thanks for looking into this

**Comment by Daomephsta** [comment] 2019-12-12 00:06
I was actually referring to a test JAR I posted in my Discord that additionally fixes #63, but it's good to know the #62 test fix JAR works.
